---
apiVersion: v1
kind: Secret
metadata:
  name: storegateway-tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDMDCCAtagAwIBAgIUKgDrQ6xu0atBMvBIpXx+LFqJ+2owCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTIzMDUwNjE1NDUwMFoXDTI0
    MDUwNTE1NDUwMFowYjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxMjAwBgNVBAMTKXN0b3JlZ2F0ZXdheS5tb25pdG9yaW5nLnN2
    Yy5jbHVzdGVyLmxvY2FsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA
    rYs25sZGw5Zy2w+ttcWL3lz6UfHyR4T6nQVacfX+y4FUD3J6gJO7CQnEIKjWw0XO
    C+AhLrIjhQreUIdQGBAglwLukBWQCIHurBIxFxRgXHf3/mVh0Z5nyV8A+zJ+eFFz
    lO6vmoANWibfqxaBkRWiGxAex94NrBuieTt3vbTcQypVI3BNbbhZgWdkissenr5Z
    XWuZAAy3BCHoS7KP/M3PA8RD6WBqabO1HV0g36MIpquQaFJ9UUw8sMZVFvTcsAJI
    YwIi0VZFk9DJM3pUtvSsZMArQEb5geaWqIWXmC9I9j06LSSFLiDBkj8YU3jhVmUF
    24XS8TFP6t1cPbLbRC4uSwIDAQABo4G2MIGzMA4GA1UdDwEB/wQEAwIFoDAdBgNV
    HSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4E
    FgQUiQRqpRz093qhEHdY8nd3E0g5+PQwHwYDVR0jBBgwFoAUDWyKHY5Snrj8MEbq
    ZJnOMxyIT7wwNAYDVR0RBC0wK4Ipc3RvcmVnYXRld2F5Lm1vbml0b3Jpbmcuc3Zj
    LmNsdXN0ZXIubG9jYWwwCgYIKoZIzj0EAwIDSAAwRQIhAJkJfJq1Ew12Mt1J/+vV
    VQ6N4rzFHq1CwVaWblo3h+BNAiAqzeUYjJcLzZSE8upLVoMfe9cVvfVfgoYY6uvZ
    aSp/lw==
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEArYs25sZGw5Zy2w+ttcWL3lz6UfHyR4T6nQVacfX+y4FUD3J6
    gJO7CQnEIKjWw0XOC+AhLrIjhQreUIdQGBAglwLukBWQCIHurBIxFxRgXHf3/mVh
    0Z5nyV8A+zJ+eFFzlO6vmoANWibfqxaBkRWiGxAex94NrBuieTt3vbTcQypVI3BN
    bbhZgWdkissenr5ZXWuZAAy3BCHoS7KP/M3PA8RD6WBqabO1HV0g36MIpquQaFJ9
    UUw8sMZVFvTcsAJIYwIi0VZFk9DJM3pUtvSsZMArQEb5geaWqIWXmC9I9j06LSSF
    LiDBkj8YU3jhVmUF24XS8TFP6t1cPbLbRC4uSwIDAQABAoIBAQCS0+4nYioM4QVc
    Ae/ekry77b58BlAN4pyGrTjQomholYshZqHulw7vnqupVjAeFrk1ovNwJpeWwJNH
    XrSNJ1frbDebACNUj1n3i4ytEjhVA8t2GSCh0XvOC+swnJAUDBXWM/uupBin5avn
    fKsyrTLx4rmoMF8w9lCIcZ/liVeyGoC0uFfb5c4Hxzj62SGkTCyviix2dyIscqa6
    70AqWulhfE78r3vO3jBuiMtNhIbamlAY/pBM2I5gBM58+LqmJxbSferu/2bcO/YC
    JlcAJWvwEE0e4Pg+0NExiK6dBVbuoO4qb96n6XTixfwUqYN9ClwV5BxxpUDHk976
    0Z43OfEBAoGBAMBWANeKzJ7JuYVoMIYnAI6lih9oTiA4zLGk9/D0LsupUu+0jNNC
    73gLfHBuO/Z0DE3Qwvg3Zn13ubpxRzMvTFLLXAH9JINgvsQk2LjhgFa4QNB+003S
    i57vzeLbs2/wELzo7U1xEWSGs3eE07nGZoqvblC/B4T/whz7Kr7YbAR7AoGBAOb8
    0Z0qjK92nIudSzzEzIZL7G0kfTXScGuXTJzrwqN8P9VKlq53IQYWhqHJkYbYFnm4
    sq0yh4vqsb/oKngNIa1gTDPBDQ35cB7+nj4GTLiP0OJZhi3rqobV9jy021g/pWTf
    nMkLNwwGqBxYIVS9xGBbHB1fU9na3spT/9nlbFxxAoGATKK4CSob5/UWv8pI81sd
    BLl+9I65+mrHXM0PoemZr7qS+kHljtPv2NQyzBWQPN32fRb+aKqiYsHOtjQmm4Vw
    EtlGmuBDqTlmKX9I/zmSynr2EF1IUoze5wBD9+10bNipwqvIyf+QX46weaHqPu6H
    syC9gtzq4RqLPMLzQEG5oHsCgYEApxr3ui/yH247ynU83PWy0OVUYZEoVCut0Ohg
    MJYO9Z8JvxB6+jSM246oT5s3gMoLWHvaJ5qKnRppBWC8eKVnW7py5m4fN6DhEEs7
    x7te/ZZtk5MYk1gOwgVAYqKknK9OxC9RidBnPngCXp8TXe77honjSQyR6OWCj/U8
    /zIOtsECgYA8S+sFl+BDPw/8F6a2PhbQe4CoZTE5PzAxTs74N2PAmMZ6CXIIBS60
    XVT2mfz1iN2nu7rdGWSEcmuy8VXUN5A+BRtXBym+WlPtJ4NeJ9/Te5C9qRJtE5Hw
    e+mQa6bReUz3wgm8VaG60k6FkBYkx93l1CBz3jIyK9f/DIEB6gVC9w==
    -----END RSA PRIVATE KEY-----
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIB2DCCAX6gAwIBAgIUAqICsMz4gYXmq+YzmHOxjZqsIkwwCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTIzMDUwNjE1MzkwMFoXDTI4
    MDUwNDE1MzkwMFowSjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxGjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMFkwEwYHKoZI
    zj0CAQYIKoZIzj0DAQcDQgAEvWbspE1iTIzDSKv41P910u8gBF7QZXrfX7I7rSXS
    Wjarz4j7f2WpQrjnhWyZM3/IjHo5v0WVye2KmcbozfgH3KNCMEAwDgYDVR0PAQH/
    BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFA1sih2OUp64/DBG6mSZ
    zjMciE+8MAoGCCqGSM49BAMCA0gAMEUCIH5W9XvaIguAQM9NTUkhF0Oe8kNgtH7v
    y64ZPojYSnqWAiEArKsmYSBtD4KcAyDGe5MrkhjqWGtvsDfVJKqfsw0sm/E=
    -----END CERTIFICATE-----
