---
apiVersion: v1
kind: Secret
metadata:
  name: storage-tls
type: kubernetes.io/tls
stringData:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDUzCCAvmgAwIBAgIUW2c3fqvgq6jW1D0XRRNiu8B1+oIwCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTIzMDUwNjAwNDEwMFoXDTI0
    MDUwNTAwNDEwMFowZDELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxNDAyBgNVBAMTK3N0b3JhZ2VnYXRld2F5Lm1vbml0b3Jpbmcu
    c3ZjLmNsdXN0ZXIubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
    AQDKFg32Sl59n8MLiPHR6czNBwVPje7yRfq8AZgyPQQLLh7QxfT9eHFBwJPd3I6E
    LUCoezJEeOBKY6qLaLxbIwKe+oX2ownrxZEgayBA2b5TZ8W05T6Z3iTQl2TZXSdW
    ycubDDTGoNzADHpp4yxTsVya+2aAJeXPB7HsIb6OvGLh9HZxJQw6GgX+CWr5mhNu
    G1fwr6o+Sr0gry7dE22+YPZBNoN6HhMe2rr7gard9WxTBHJG+u9roZ61q6NB9tnF
    i4Hyf2+bFMYWAx0Uu+moE5bapudPFOVwfl/qrajzbdRZ76Q1FwM/d/sqdpgRUkrc
    miLA+EjTVhSZYNpJAjEABPiXAgMBAAGjgdcwgdQwDgYDVR0PAQH/BAQDAgWgMB0G
    A1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1Ud
    DgQWBBRxvSrFcAAT+5QiILitm77MJRqdzDAfBgNVHSMEGDAWgBQ13UYdoPuxqNyK
    ptTwVzsLnOE94jBVBgNVHREETjBMgitzdG9yYWdlZ2F0ZXdheS5tb25pdG9yaW5n
    LnN2Yy5jbHVzdGVyLmxvY2Fsgh1zdG9yYWdlZ2F0ZXdheS5hbnRvbnB1dHJhLmNv
    bTAKBggqhkjOPQQDAgNIADBFAiEAlhVt7IGWluyUsdl5mAiKA9M8VIqD9oL4l4Qc
    dX7oVkgCIDSWcAqPbuZc6ARH70/3o7JSd7+BRRPtzRk4Y4D78+kR
    -----END CERTIFICATE-----
  tls.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAyhYN9kpefZ/DC4jx0enMzQcFT43u8kX6vAGYMj0ECy4e0MX0
    /XhxQcCT3dyOhC1AqHsyRHjgSmOqi2i8WyMCnvqF9qMJ68WRIGsgQNm+U2fFtOU+
    md4k0Jdk2V0nVsnLmww0xqDcwAx6aeMsU7FcmvtmgCXlzwex7CG+jrxi4fR2cSUM
    OhoF/glq+ZoTbhtX8K+qPkq9IK8u3RNtvmD2QTaDeh4THtq6+4Gq3fVsUwRyRvrv
    a6GetaujQfbZxYuB8n9vmxTGFgMdFLvpqBOW2qbnTxTlcH5f6q2o823UWe+kNRcD
    P3f7KnaYEVJK3JoiwPhI01YUmWDaSQIxAAT4lwIDAQABAoIBAQDHk35YdNvarvP+
    KVHAoGitNzjMd3y68deM4vo+6zlaHUM7pbSsus0HRbwCiPaKnPJVMc3UB5hifwmH
    wnj6fJnzDbFNgXijyyrnXESvJxuq3TpIy3nGlbe/9TQY4sGeGY6l4ikg3O8GD4y5
    lCxLv0aYnJ1/A25wxsW1USITbwMs5/Geh0/EAmptBZx6pu2CCfMobn1b71cyLU8w
    CjrY+9f7bWk/m5KzV1cf8Mq+l7VqjahlvyxaR+UGdWm3wvqffjAHs6xOZnyOEDHn
    6/SBl/GNcC6403irmuVtqpVeBPLTlKRCzeGs+WAeRYJYTTQ+cncjjfKcI+P/WOyU
    YwXc/xNpAoGBAPVoV7GH+zRoTIFUCx3KZ5FQknsdYxoToaeRQD2v8caNksw1c73K
    IpGLJoNZtdW+tjE5KLR8S2lC9R+84FQF7Ceip/WKPLfMlcc1eSCdpOVabIw3slha
    7b3aE6W4dtyht9dT6yx/hcd1R6Qw01JNL8fXqJm9xj0veCG6lK182H/jAoGBANLP
    BvFKDSL+16oafuuKqs/2YoODd/Q9X3ou1LDxiboFpL/f+sFtF4XRc5dwTcuwtmTU
    Bx7NiqKjHs6ONcuuPVaD5RVEqNFQPTgYlPaXi2J43j9qfERBMqKDdsdNCg17znqP
    S61htuRCOTzsqxQXMdnhhNnEBWKRmNbxnu0vwJq9AoGBALwEtGM0/rZ5TlwrqtSp
    NU41P/UJX9sjvU+nzmM0wPVRlG3WahW3n2KJDPnHqrPXiLkPxOr667/659joGarm
    WrdHPI232qsrGHnmsyXVAfginlWTepWNHOa/BRyLxq1lTXexONX/4dweM8RNECrX
    LktbJDaeGhrYmp6k17JPm4PnAoGAauA++tG6O0XMfRcVxcD1vJ2DcH2UsST0ZPOd
    LWAnnUIDNqwNa0ctp9B6tAphxqT+s7uzKHC4mp/snHgI2gyqWFRiLhgzJntxriD4
    VNSb+/6fXrNT8R7E1xOjgoOSVyevlP9VNL/Xg333muW6DmN8CKSHQAhbWo/KVx8E
    neeZ1FkCgYEA8Ox0bJ+D3inHkWxuU3TW6moSuhqm4Xshr5udqKWOB3XBmacp/Glh
    t4MPfM/vSkZjoNu2S9ZH1u6XCa48hq7jYZ4v8X6CaKEelv1y49wS+HSrVicDu5R8
    w4Kl7xJ3wFw3VreW6wHkXpft97OwgsqDuDrNINFT7pgdlYMLuXFhJgw=
    -----END RSA PRIVATE KEY-----
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIB2DCCAX6gAwIBAgIUYr50d8FDsaAQD63A5pfxPZSc5L4wCgYIKoZIzj0EAwIw
    SjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQHEwlMb3MgQmFub3Mx
    GjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMB4XDTIzMDUwNTIyNTcwMFoXDTI4
    MDUwMzIyNTcwMFowSjELMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRIwEAYDVQQH
    EwlMb3MgQmFub3MxGjAYBgNVBAMTEURldk9wcyBieSBFeGFtcGxlMFkwEwYHKoZI
    zj0CAQYIKoZIzj0DAQcDQgAEFfgiuFgQCzs7tJCkom0OY0ZsjDwtqxy3onpnIFrP
    c1HM3UjjDff7AUnRSpqBUCW6Q4OE+PAdwTqskMtPkv34maNCMEAwDgYDVR0PAQH/
    BAQDAgEGMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFDXdRh2g+7Go3Iqm1PBX
    Owuc4T3iMAoGCCqGSM49BAMCA0gAMEUCIFZNfP4DTt8uZMhOxgtL0ZPnnw7r77u9
    JULmJULHkjvmAiEAjU7Nzv487JwFrioMnJ4HAURsqwjRBa7NMFGt1+ODs0o=
    -----END CERTIFICATE-----
